language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always