language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always
env:
  global:
  - 'USER_SCP=[user_scp]'
  - 'PASS_SCP=[pass_scp]'
after_success:
  - scp ./build/* ${USER_SCP}@${PASS_SCP}:/home/dados-colombo/site/build